/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package laboratoriotresjava;

/**
 *
 * @author Admin
 */
public class VentanaSecundaria extends javax.swing.JDialog {

    /**
     * Creates new form VentanaSecundaria
     */
    public VentanaSecundaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelFila = new javax.swing.JPanel();
        lblNumeracion1 = new javax.swing.JLabel();
        lblNumeracion2 = new javax.swing.JLabel();
        PanelColumna = new javax.swing.JPanel();
        PanelMatriz = new javax.swing.JPanel();
        lblMatriz3 = new javax.swing.JLabel();
        lblMatriz1 = new javax.swing.JLabel();
        lblMatriz4 = new javax.swing.JLabel();
        lblMatriz2 = new javax.swing.JLabel();
        lblMatriz5 = new javax.swing.JLabel();
        lblMatriz7 = new javax.swing.JLabel();
        lblMatriz6 = new javax.swing.JLabel();
        lblMatriz8 = new javax.swing.JLabel();
        lblMatriz9 = new javax.swing.JLabel();
        lblMatriz10 = new javax.swing.JLabel();
        lblMatriz11 = new javax.swing.JLabel();
        lblMatriz12 = new javax.swing.JLabel();
        lblMatriz13 = new javax.swing.JLabel();
        lblMatriz14 = new javax.swing.JLabel();
        lblMatriz15 = new javax.swing.JLabel();
        lblMatriz16 = new javax.swing.JLabel();
        lblMatriz17 = new javax.swing.JLabel();
        lblMatriz18 = new javax.swing.JLabel();
        lblMatriz19 = new javax.swing.JLabel();
        lblMatriz20 = new javax.swing.JLabel();
        lblMatriz21 = new javax.swing.JLabel();
        lblMatriz22 = new javax.swing.JLabel();
        lblMatriz23 = new javax.swing.JLabel();
        lblMatriz24 = new javax.swing.JLabel();
        lblMatriz25 = new javax.swing.JLabel();
        lblMatriz26 = new javax.swing.JLabel();
        lblMatriz27 = new javax.swing.JLabel();
        lblMatriz28 = new javax.swing.JLabel();
        lblMatriz29 = new javax.swing.JLabel();
        lblMatriz30 = new javax.swing.JLabel();
        lblMatriz31 = new javax.swing.JLabel();
        lblMatriz32 = new javax.swing.JLabel();
        lblMatriz33 = new javax.swing.JLabel();
        lblMatriz34 = new javax.swing.JLabel();
        lblMatriz35 = new javax.swing.JLabel();
        lblMatriz36 = new javax.swing.JLabel();
        lblMatriz37 = new javax.swing.JLabel();
        lblMatriz38 = new javax.swing.JLabel();
        lblMatriz39 = new javax.swing.JLabel();
        lblMatriz40 = new javax.swing.JLabel();
        lblMatriz41 = new javax.swing.JLabel();
        lblMatriz42 = new javax.swing.JLabel();
        lblMatriz43 = new javax.swing.JLabel();
        lblMatriz44 = new javax.swing.JLabel();
        lblMatriz45 = new javax.swing.JLabel();
        lblMatriz46 = new javax.swing.JLabel();
        lblMatriz47 = new javax.swing.JLabel();
        lblMatriz48 = new javax.swing.JLabel();
        lblMatriz49 = new javax.swing.JLabel();
        lblMatriz50 = new javax.swing.JLabel();
        lblMatriz51 = new javax.swing.JLabel();
        lblMatriz52 = new javax.swing.JLabel();
        lblMatriz53 = new javax.swing.JLabel();
        lblMatriz54 = new javax.swing.JLabel();
        lblMatriz55 = new javax.swing.JLabel();
        lblMatriz56 = new javax.swing.JLabel();
        lblMatriz57 = new javax.swing.JLabel();
        lblMatriz58 = new javax.swing.JLabel();
        lblMatriz59 = new javax.swing.JLabel();
        lblMatriz60 = new javax.swing.JLabel();
        lblMatriz61 = new javax.swing.JLabel();
        lblMatriz62 = new javax.swing.JLabel();
        lblMatriz63 = new javax.swing.JLabel();
        lblMatriz64 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblNumeracion1.setText("0");

        lblNumeracion2.setText("0");

        javax.swing.GroupLayout PanelFilaLayout = new javax.swing.GroupLayout(PanelFila);
        PanelFila.setLayout(PanelFilaLayout);
        PanelFilaLayout.setHorizontalGroup(
            PanelFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFilaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNumeracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelFilaLayout.setVerticalGroup(
            PanelFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNumeracion2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(lblNumeracion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelColumnaLayout = new javax.swing.GroupLayout(PanelColumna);
        PanelColumna.setLayout(PanelColumnaLayout);
        PanelColumnaLayout.setHorizontalGroup(
            PanelColumnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        PanelColumnaLayout.setVerticalGroup(
            PanelColumnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        PanelMatriz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMatriz3.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz3.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz3.setOpaque(true);
        PanelMatriz.add(lblMatriz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 46));

        lblMatriz1.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz1.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz1.setOpaque(true);
        PanelMatriz.add(lblMatriz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 46));

        lblMatriz4.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz4.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz4.setOpaque(true);
        PanelMatriz.add(lblMatriz4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 46));

        lblMatriz2.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz2.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz2.setOpaque(true);
        PanelMatriz.add(lblMatriz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 60, 46));

        lblMatriz5.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz5.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz5.setOpaque(true);
        PanelMatriz.add(lblMatriz5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 60, 46));

        lblMatriz7.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz7.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz7.setOpaque(true);
        PanelMatriz.add(lblMatriz7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 60, 46));

        lblMatriz6.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz6.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz6.setOpaque(true);
        PanelMatriz.add(lblMatriz6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 60, 46));

        lblMatriz8.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz8.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz8.setOpaque(true);
        PanelMatriz.add(lblMatriz8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 46));

        lblMatriz9.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz9.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz9.setOpaque(true);
        PanelMatriz.add(lblMatriz9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 46));

        lblMatriz10.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz10.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz10.setOpaque(true);
        PanelMatriz.add(lblMatriz10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, 46));

        lblMatriz11.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz11.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz11.setOpaque(true);
        PanelMatriz.add(lblMatriz11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, 46));

        lblMatriz12.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz12.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz12.setOpaque(true);
        PanelMatriz.add(lblMatriz12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 60, 46));

        lblMatriz13.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz13.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz13.setOpaque(true);
        PanelMatriz.add(lblMatriz13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 60, 46));

        lblMatriz14.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz14.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz14.setOpaque(true);
        PanelMatriz.add(lblMatriz14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 60, 46));

        lblMatriz15.setBackground(new java.awt.Color(255, 51, 51));
        lblMatriz15.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz15.setOpaque(true);
        PanelMatriz.add(lblMatriz15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 60, 46));

        lblMatriz16.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz16.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz16.setOpaque(true);
        PanelMatriz.add(lblMatriz16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, 46));

        lblMatriz17.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz17.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz17.setOpaque(true);
        PanelMatriz.add(lblMatriz17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 60, 46));

        lblMatriz18.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz18.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz18.setOpaque(true);
        PanelMatriz.add(lblMatriz18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, 46));

        lblMatriz19.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz19.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz19.setOpaque(true);
        PanelMatriz.add(lblMatriz19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, 46));

        lblMatriz20.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz20.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz20.setOpaque(true);
        PanelMatriz.add(lblMatriz20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 60, 46));

        lblMatriz21.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz21.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz21.setOpaque(true);
        PanelMatriz.add(lblMatriz21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 46));

        lblMatriz22.setBackground(new java.awt.Color(0, 153, 51));
        lblMatriz22.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMatriz22.setOpaque(true);
        PanelMatriz.add(lblMatriz22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 60, 46));

        lblMatriz23.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz23.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz23.setOpaque(true);
        PanelMatriz.add(lblMatriz23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 60, 46));

        lblMatriz24.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz24.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz24.setOpaque(true);
        PanelMatriz.add(lblMatriz24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 60, 46));

        lblMatriz25.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz25.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz25.setOpaque(true);
        PanelMatriz.add(lblMatriz25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 60, 46));

        lblMatriz26.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz26.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz26.setOpaque(true);
        PanelMatriz.add(lblMatriz26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, 46));

        lblMatriz27.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz27.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz27.setOpaque(true);
        PanelMatriz.add(lblMatriz27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 60, 46));

        lblMatriz28.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz28.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz28.setOpaque(true);
        PanelMatriz.add(lblMatriz28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 60, 46));

        lblMatriz29.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz29.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz29.setOpaque(true);
        PanelMatriz.add(lblMatriz29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 60, 46));

        lblMatriz30.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz30.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz30.setOpaque(true);
        PanelMatriz.add(lblMatriz30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 60, 46));

        lblMatriz31.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz31.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz31.setOpaque(true);
        PanelMatriz.add(lblMatriz31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, 46));

        lblMatriz32.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz32.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz32.setOpaque(true);
        PanelMatriz.add(lblMatriz32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 60, 46));

        lblMatriz33.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz33.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz33.setOpaque(true);
        PanelMatriz.add(lblMatriz33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 60, 46));

        lblMatriz34.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz34.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz34.setOpaque(true);
        PanelMatriz.add(lblMatriz34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 60, 46));

        lblMatriz35.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz35.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz35.setOpaque(true);
        PanelMatriz.add(lblMatriz35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 60, 46));

        lblMatriz36.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz36.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz36.setOpaque(true);
        PanelMatriz.add(lblMatriz36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 60, 46));

        lblMatriz37.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz37.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz37.setOpaque(true);
        PanelMatriz.add(lblMatriz37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 60, 46));

        lblMatriz38.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz38.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz38.setOpaque(true);
        PanelMatriz.add(lblMatriz38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, 46));

        lblMatriz39.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz39.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz39.setOpaque(true);
        PanelMatriz.add(lblMatriz39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 60, 46));

        lblMatriz40.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz40.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz40.setOpaque(true);
        PanelMatriz.add(lblMatriz40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 60, 46));

        lblMatriz41.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz41.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz41.setOpaque(true);
        PanelMatriz.add(lblMatriz41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 60, 46));

        lblMatriz42.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz42.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz42.setOpaque(true);
        PanelMatriz.add(lblMatriz42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 60, 46));

        lblMatriz43.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz43.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz43.setOpaque(true);
        PanelMatriz.add(lblMatriz43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 60, 46));

        lblMatriz44.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz44.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz44.setOpaque(true);
        PanelMatriz.add(lblMatriz44, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, 46));

        lblMatriz45.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz45.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz45.setOpaque(true);
        PanelMatriz.add(lblMatriz45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 60, 46));

        lblMatriz46.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz46.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz46.setOpaque(true);
        PanelMatriz.add(lblMatriz46, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 60, 46));

        lblMatriz47.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz47.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz47.setOpaque(true);
        PanelMatriz.add(lblMatriz47, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 60, 46));

        lblMatriz48.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz48.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz48.setOpaque(true);
        PanelMatriz.add(lblMatriz48, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 60, 46));

        lblMatriz49.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz49.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz49.setOpaque(true);
        PanelMatriz.add(lblMatriz49, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 60, 46));

        lblMatriz50.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz50.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz50.setOpaque(true);
        PanelMatriz.add(lblMatriz50, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 60, 46));

        lblMatriz51.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz51.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz51.setOpaque(true);
        PanelMatriz.add(lblMatriz51, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 60, 46));

        lblMatriz52.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz52.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz52.setOpaque(true);
        PanelMatriz.add(lblMatriz52, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 60, 46));

        lblMatriz53.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz53.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz53.setOpaque(true);
        PanelMatriz.add(lblMatriz53, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, 46));

        lblMatriz54.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz54.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz54.setOpaque(true);
        PanelMatriz.add(lblMatriz54, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, 46));

        lblMatriz55.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz55.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz55.setOpaque(true);
        PanelMatriz.add(lblMatriz55, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 60, 46));

        lblMatriz56.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz56.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz56.setOpaque(true);
        PanelMatriz.add(lblMatriz56, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 60, 46));

        lblMatriz57.setBackground(new java.awt.Color(153, 153, 153));
        lblMatriz57.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz57.setOpaque(true);
        PanelMatriz.add(lblMatriz57, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 60, 46));

        lblMatriz58.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz58.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz58.setOpaque(true);
        PanelMatriz.add(lblMatriz58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 60, 46));

        lblMatriz59.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz59.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz59.setOpaque(true);
        PanelMatriz.add(lblMatriz59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 60, 46));

        lblMatriz60.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz60.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz60.setOpaque(true);
        PanelMatriz.add(lblMatriz60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 60, 46));

        lblMatriz61.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz61.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz61.setOpaque(true);
        PanelMatriz.add(lblMatriz61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 60, 46));

        lblMatriz62.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz62.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz62.setOpaque(true);
        PanelMatriz.add(lblMatriz62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 60, 46));

        lblMatriz63.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz63.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz63.setOpaque(true);
        PanelMatriz.add(lblMatriz63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 60, 46));

        lblMatriz64.setBackground(new java.awt.Color(0, 153, 153));
        lblMatriz64.setBorder(new javax.swing.border.MatteBorder(null));
        lblMatriz64.setOpaque(true);
        PanelMatriz.add(lblMatriz64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 60, 46));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(PanelColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(PanelFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addComponent(PanelMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(PanelFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaSecundaria dialog = new VentanaSecundaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelColumna;
    private javax.swing.JPanel PanelFila;
    private javax.swing.JPanel PanelMatriz;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel lblMatriz1;
    private javax.swing.JLabel lblMatriz10;
    private javax.swing.JLabel lblMatriz11;
    private javax.swing.JLabel lblMatriz12;
    private javax.swing.JLabel lblMatriz13;
    private javax.swing.JLabel lblMatriz14;
    private javax.swing.JLabel lblMatriz15;
    private javax.swing.JLabel lblMatriz16;
    private javax.swing.JLabel lblMatriz17;
    private javax.swing.JLabel lblMatriz18;
    private javax.swing.JLabel lblMatriz19;
    private javax.swing.JLabel lblMatriz2;
    private javax.swing.JLabel lblMatriz20;
    private javax.swing.JLabel lblMatriz21;
    private javax.swing.JLabel lblMatriz22;
    private javax.swing.JLabel lblMatriz23;
    private javax.swing.JLabel lblMatriz24;
    private javax.swing.JLabel lblMatriz25;
    private javax.swing.JLabel lblMatriz26;
    private javax.swing.JLabel lblMatriz27;
    private javax.swing.JLabel lblMatriz28;
    private javax.swing.JLabel lblMatriz29;
    private javax.swing.JLabel lblMatriz3;
    private javax.swing.JLabel lblMatriz30;
    private javax.swing.JLabel lblMatriz31;
    private javax.swing.JLabel lblMatriz32;
    private javax.swing.JLabel lblMatriz33;
    private javax.swing.JLabel lblMatriz34;
    private javax.swing.JLabel lblMatriz35;
    private javax.swing.JLabel lblMatriz36;
    private javax.swing.JLabel lblMatriz37;
    private javax.swing.JLabel lblMatriz38;
    private javax.swing.JLabel lblMatriz39;
    private javax.swing.JLabel lblMatriz4;
    private javax.swing.JLabel lblMatriz40;
    private javax.swing.JLabel lblMatriz41;
    private javax.swing.JLabel lblMatriz42;
    private javax.swing.JLabel lblMatriz43;
    private javax.swing.JLabel lblMatriz44;
    private javax.swing.JLabel lblMatriz45;
    private javax.swing.JLabel lblMatriz46;
    private javax.swing.JLabel lblMatriz47;
    private javax.swing.JLabel lblMatriz48;
    private javax.swing.JLabel lblMatriz49;
    private javax.swing.JLabel lblMatriz5;
    private javax.swing.JLabel lblMatriz50;
    private javax.swing.JLabel lblMatriz51;
    private javax.swing.JLabel lblMatriz52;
    private javax.swing.JLabel lblMatriz53;
    private javax.swing.JLabel lblMatriz54;
    private javax.swing.JLabel lblMatriz55;
    private javax.swing.JLabel lblMatriz56;
    private javax.swing.JLabel lblMatriz57;
    private javax.swing.JLabel lblMatriz58;
    private javax.swing.JLabel lblMatriz59;
    private javax.swing.JLabel lblMatriz6;
    private javax.swing.JLabel lblMatriz60;
    private javax.swing.JLabel lblMatriz61;
    private javax.swing.JLabel lblMatriz62;
    private javax.swing.JLabel lblMatriz63;
    private javax.swing.JLabel lblMatriz64;
    private javax.swing.JLabel lblMatriz7;
    private javax.swing.JLabel lblMatriz8;
    private javax.swing.JLabel lblMatriz9;
    private javax.swing.JLabel lblNumeracion1;
    private javax.swing.JLabel lblNumeracion2;
    // End of variables declaration//GEN-END:variables
}
